apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  annotations:
     serving.kubeflow.org/s3-endpoint: s3.amazonaws.com # replace with your s3 endpoint
     serving.kubeflow.org/s3-usehttps: "1" # by default 1, for testing with minio you need to set to 0
type: Opaque
stringData:
  awsAccessKeyID: AKIAJFFDI3UU6OO6SH2A
  awsSecretAccessKey: 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
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa
secrets:
  - name: mysecret