apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "sklearn-iris-svm-s3-secret-3"
spec:
  default:
    predictor:
      serviceAccountName: sa
      sklearn:
        storageUri: "s3://pattersonconsulting/kubeflow/kfserving/models/sklearn"