apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "aws-sklearn-model"
spec:
  default:
    predictor:
      serviceAccountName: sa
      minReplicas: 1
      sklearn:
        storageUri: "s3://pattersonconsulting/kubeflow/kfserving/models/sklearn"