apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "my-tf-flowers-model"
spec:
  default: 
    predictor:
      minReplicas: 1
      tensorflow:
        storageUri: "gs://kfserving-samples/models/tensorflow/flowers-2"

